// Petit Lenormand : les 36 cartes, les tirages et le livret.
// Textes originaux : le sens traditionnel des cartes est conservé, la formulation est propre au grimoire.
// nom : la carte vue comme un « sujet » ; mod : la carte vue comme une nuance (lecture en paires).

export const THEMES = {
  amour: 'd’amour et de sentiments',
  relations: 'de relations et d’entourage',
  travail: 'de travail et de projets',
  argent: 'd’argent et de ressources',
  communication: 'de communication et de nouvelles',
  foyer: 'de foyer et de famille',
  changement: 'de changement et de mouvement',
  obstacles: 'de freins et de défis à relever',
  spirituel: 'de sens et de vie intérieure',
  sante: 'd’énergie et de bien-être',
  chance: 'de chance et d’opportunités',
};

export const CARDS = [
  null,
  { n: 1, name: 'Le Cavalier', pc: '9♥', tone: 1, themes: ['communication', 'changement'],
    kw: ['Nouvelles', 'Mouvement', 'Visite', 'Rapidité'],
    sens: 'Quelque chose se met en route : une information, une visite ou une occasion arrive bientôt. Le Cavalier accélère le rythme et apporte plutôt de bonnes nouvelles.',
    amour: 'Une rencontre ou un message du cœur peut surgir sans prévenir.',
    travail: 'Une réponse, un contact ou un déplacement fait avancer les choses.',
    conseil: 'Reste disponible : ce qui arrive demande une réaction rapide.',
    nom: 'une nouvelle en approche', mod: 'qui arrive rapidement' },
  { n: 2, name: 'Le Trèfle', pc: '6♦', tone: 1, themes: ['chance'],
    kw: ['Petite chance', 'Occasion', 'Légèreté', 'Sourire'],
    sens: 'Une chance se présente, souvent brève. Le Trèfle invite à saisir l’occasion avant qu’elle ne passe et à garder une humeur légère face aux petits aléas.',
    amour: 'Un moment joyeux, un flirt, une embellie passagère.',
    travail: 'Une ouverture inattendue, à saisir sans tarder.',
    conseil: 'Saisis l’occasion tant qu’elle est là.',
    nom: 'un coup de chance', mod: 'qui apporte un peu de chance' },
  { n: 3, name: 'Le Navire', pc: '10♠', tone: 0, themes: ['changement', 'argent'],
    kw: ['Voyage', 'Distance', 'Horizon', 'Échanges'],
    sens: 'Le Navire parle d’éloignement et d’horizon : un voyage, un projet lointain, une envie de changer d’air. Il évoque aussi le commerce et ce qui vient de loin.',
    amour: 'Une relation à distance ou le désir de nouveauté.',
    travail: 'Commerce, mobilité, projet qui prend le large.',
    conseil: 'Ose élargir ton horizon.',
    nom: 'un voyage ou un départ', mod: 'qui mène vers l’ailleurs' },
  { n: 4, name: 'La Maison', pc: 'R♥', tone: 1, themes: ['foyer'],
    kw: ['Foyer', 'Famille', 'Sécurité', 'Stabilité'],
    sens: 'La Maison représente le cocon : la famille, le logement, tout ce qui rassure. Elle apporte stabilité et protection, et rappelle l’importance des racines.',
    amour: 'Une relation qui se pose, le projet de vivre ensemble.',
    travail: 'Un cadre solide, une entreprise familiale, le travail à domicile.',
    conseil: 'Prends appui sur ce qui te sécurise.',
    nom: 'le foyer', mod: 'qui s’installe dans la stabilité' },
  { n: 5, name: 'L’Arbre', pc: '7♥', tone: 0, themes: ['sante', 'spirituel'],
    kw: ['Santé', 'Croissance', 'Racines', 'Patience'],
    sens: 'L’Arbre pousse lentement mais sûrement. Il parle de vitalité, de santé, d’héritage familial et de tout ce qui demande du temps pour s’épanouir.',
    amour: 'Un lien qui se construit dans la durée, avec patience.',
    travail: 'Un projet de long terme, à cultiver sans se presser.',
    conseil: 'Prends soin de ton énergie et laisse le temps agir.',
    nom: 'une croissance lente et profonde', mod: 'qui s’enracine avec le temps' },
  { n: 6, name: 'Les Nuages', pc: 'R♣', tone: -1, themes: ['obstacles'],
    kw: ['Doute', 'Confusion', 'Incertitude', 'Humeur changeante'],
    sens: 'Les Nuages voilent la vue : doutes, malentendus, humeur instable. La situation manque de clarté pour l’instant, mais aucun nuage ne reste éternellement.',
    amour: 'Des hésitations ou des malentendus brouillent le lien.',
    travail: 'Des informations floues : mieux vaut vérifier avant d’agir.',
    conseil: 'Attends que le ciel s’éclaircisse avant de trancher.',
    nom: 'une période de doute', mod: 'qui manque encore de clarté' },
  { n: 7, name: 'Le Serpent', pc: 'D♣', tone: -1, themes: ['obstacles', 'relations'],
    kw: ['Détour', 'Complication', 'Désir', 'Rivalité'],
    sens: 'Le Serpent annonce des chemins sinueux : rien ne se fait en ligne droite. Il peut désigner une personne habile, une rivalité ou un désir puissant, et demande de la vigilance.',
    amour: 'Jalousie, séduction intense ou tierce personne.',
    travail: 'Négociations tortueuses, jeux d’influence.',
    conseil: 'Reste lucide et avance avec finesse.',
    nom: 'une situation compliquée', mod: 'qui prend des détours' },
  { n: 8, name: 'Le Cercueil', pc: '9♦', tone: -1, themes: ['changement', 'sante'],
    kw: ['Fin', 'Pause', 'Transformation', 'Fatigue'],
    sens: 'Le Cercueil marque la fin d’un cycle : une page se tourne, une pause s’impose, la fatigue demande du repos. Ce n’est pas une menace, mais une clôture qui prépare un renouveau.',
    amour: 'Une relation qui s’achève ou qui doit se réinventer.',
    travail: 'Un projet qui se termine, un besoin de souffler.',
    conseil: 'Accepte de laisser partir ce qui est terminé.',
    nom: 'une fin nécessaire', mod: 'qui touche à sa fin' },
  { n: 9, name: 'Le Bouquet', pc: 'D♠', tone: 1, themes: ['chance', 'relations'],
    kw: ['Cadeau', 'Joie', 'Gratitude', 'Invitation'],
    sens: 'Le Bouquet offre ses fleurs : un cadeau, un compliment, une invitation ou un moment de bonheur. Il apporte beauté, reconnaissance et bonne humeur.',
    amour: 'Des attentions, des mots doux, des moments tendres.',
    travail: 'Félicitations, reconnaissance, belle ambiance.',
    conseil: 'Accueille ce qui t’est offert et partage-le.',
    nom: 'un joli cadeau', mod: 'qui apporte de la joie' },
  { n: 10, name: 'La Faux', pc: 'V♦', tone: -1, themes: ['changement', 'obstacles'],
    kw: ['Décision nette', 'Imprévu', 'Coupure', 'Récolte'],
    sens: 'La Faux tranche net : une décision rapide, un événement soudain, une séparation. Elle annonce aussi le temps de la récolte, quand il faut couper pour cueillir. Attention aux gestes précipités.',
    amour: 'Une séparation ou une décision radicale.',
    travail: 'Un changement brusque, un choix à faire vite.',
    conseil: 'Tranche si tu le dois, mais sans te blesser.',
    nom: 'une décision tranchée', mod: 'qui survient soudainement' },
  { n: 11, name: 'Le Fouet', pc: 'V♣', tone: -1, themes: ['relations', 'obstacles'],
    kw: ['Dispute', 'Répétition', 'Effort', 'Passion'],
    sens: 'Le Fouet évoque les échanges vifs, les querelles ou les schémas qui se répètent. Il parle aussi d’effort physique, de sport ou de passion : l’énergie est forte et gagne à être canalisée.',
    amour: 'Des disputes, ou au contraire une passion intense.',
    travail: 'Débats animés, critiques, tâches répétitives.',
    conseil: 'Transforme la tension en énergie constructive.',
    nom: 'un conflit', mod: 'qui suscite des échanges vifs' },
  { n: 12, name: 'Les Oiseaux', pc: '7♦', tone: 0, themes: ['communication', 'relations'],
    kw: ['Conversation', 'Échanges', 'Agitation', 'Duo'],
    sens: 'Les Oiseaux bavardent : appels, discussions, rumeurs, parfois un peu de nervosité. Ils évoquent aussi le duo, deux personnes qui se parlent.',
    amour: 'Des échanges fréquents, des discussions à deux.',
    travail: 'Réunions, négociations, bruits de couloir.',
    conseil: 'Parle franchement et écoute vraiment.',
    nom: 'une conversation', mod: 'qui fait beaucoup parler' },
  { n: 13, name: 'L’Enfant', pc: 'V♠', tone: 1, themes: ['changement', 'foyer'],
    kw: ['Début', 'Nouveauté', 'Spontanéité', 'Jeunesse'],
    sens: 'L’Enfant apporte fraîcheur et spontanéité : un commencement, un petit projet, un regard neuf. Il peut aussi désigner un enfant ou une personne jeune.',
    amour: 'Une relation naissante, pleine de candeur.',
    travail: 'Un projet qui démarre, une personne qui débute.',
    conseil: 'Ose commencer, même modestement.',
    nom: 'un nouveau départ', mod: 'qui commence tout juste' },
  { n: 14, name: 'Le Renard', pc: '9♣', tone: -1, themes: ['travail', 'obstacles'],
    kw: ['Ruse', 'Prudence', 'Stratégie', 'Débrouillardise'],
    sens: 'Le Renard est malin : il met en garde contre ce qui n’est pas tout à fait sincère, et invite aussi à utiliser sa propre intelligence. Il est souvent lié au travail et au sens pratique.',
    amour: 'Un doute sur la sincérité, un besoin de prudence.',
    travail: 'Le quotidien professionnel, la stratégie, la concurrence.',
    conseil: 'Fie-toi à ton flair et vérifie les détails.',
    nom: 'une manœuvre habile', mod: 'qui cache une intention' },
  { n: 15, name: 'L’Ours', pc: '10♣', tone: 0, themes: ['argent', 'travail'],
    kw: ['Force', 'Pouvoir', 'Protection', 'Réserves'],
    sens: 'L’Ours est puissant : il représente la force, l’autorité, les ressources et parfois une personne protectrice ou imposante, comme un chef ou une figure parentale. Il parle aussi d’argent mis de côté.',
    amour: 'Une protection, ou au contraire de la possessivité.',
    travail: 'Un supérieur, un investissement, une position de pouvoir.',
    conseil: 'Sers-toi de ta force pour protéger, jamais pour écraser.',
    nom: 'une force protectrice', mod: 'qui s’appuie sur le pouvoir' },
  { n: 16, name: 'Les Étoiles', pc: '6♥', tone: 1, themes: ['spirituel', 'chance'],
    kw: ['Espoir', 'Inspiration', 'Guidance', 'Clarté'],
    sens: 'Les Étoiles éclairent la route : espoir, inspiration, confiance en l’avenir. Elles parlent d’objectifs, de spiritualité et de vœux qui se réalisent.',
    amour: 'Un lien inspirant, un vœu qui s’exauce.',
    travail: 'Une vision claire, un projet qui rayonne, le monde numérique.',
    conseil: 'Garde les yeux fixés sur ton étoile.',
    nom: 'un espoir lumineux', mod: 'qui guide vers les rêves' },
  { n: 17, name: 'La Cigogne', pc: 'D♥', tone: 1, themes: ['changement', 'foyer'],
    kw: ['Évolution', 'Renouveau', 'Amélioration', 'Déménagement'],
    sens: 'La Cigogne apporte du nouveau : une évolution, un déménagement, une amélioration. Les choses bougent dans le bon sens et un cycle se renouvelle.',
    amour: 'Une relation qui évolue, une étape franchie ensemble.',
    travail: 'Promotion, réorganisation, nouveau poste.',
    conseil: 'Accompagne le changement au lieu de le freiner.',
    nom: 'un changement heureux', mod: 'qui fait évoluer les choses' },
  { n: 18, name: 'Le Chien', pc: '10♥', tone: 1, themes: ['relations'],
    kw: ['Amitié', 'Fidélité', 'Soutien', 'Confiance'],
    sens: 'Le Chien est l’ami sincère : loyauté, soutien, confiance. Il désigne souvent un proche sur qui l’on peut compter.',
    amour: 'Fidélité, complicité, un lien sûr.',
    travail: 'Un collègue fiable, un allié, une bonne collaboration.',
    conseil: 'Appuie-toi sur tes vrais amis.',
    nom: 'un ami fidèle', mod: 'qui inspire confiance' },
  { n: 19, name: 'La Tour', pc: '6♠', tone: 0, themes: ['travail'],
    kw: ['Institution', 'Autorité', 'Recul', 'Solitude'],
    sens: 'La Tour se dresse seule : administrations, grandes entreprises, autorité, mais aussi besoin de solitude et de recul. Elle parle de structure et de ce qui dure.',
    amour: 'Une distance émotionnelle, un besoin d’espace.',
    travail: 'Grande structure, démarche officielle, hiérarchie.',
    conseil: 'Prends de la hauteur pour voir plus loin.',
    nom: 'une institution', mod: 'qui prend de la hauteur' },
  { n: 20, name: 'Le Jardin', pc: '8♠', tone: 1, themes: ['relations'],
    kw: ['Vie sociale', 'Public', 'Réseau', 'Sorties'],
    sens: 'Le Jardin ouvre sur les autres : sorties, fêtes, réseaux, vie publique. Il invite à se montrer, à rencontrer et à partager.',
    amour: 'Une rencontre lors d’une sortie ou d’un événement.',
    travail: 'Réseau, clientèle, visibilité, salons.',
    conseil: 'Sors de ta bulle et va vers les autres.',
    nom: 'une rencontre en société', mod: 'qui se partage avec les autres' },
  { n: 21, name: 'La Montagne', pc: '8♣', tone: -1, themes: ['obstacles'],
    kw: ['Obstacle', 'Retard', 'Blocage', 'Endurance'],
    sens: 'La Montagne barre la route : retard, difficulté, blocage. Elle ne dit pas « non » mais « pas tout de suite », et demande de la persévérance ou un détour.',
    amour: 'Un frein, une froideur, une distance à franchir.',
    travail: 'Retards, lenteurs administratives, défi de taille.',
    conseil: 'Avance pas à pas : chaque effort compte.',
    nom: 'un obstacle', mod: 'qui demande de la patience' },
  { n: 22, name: 'Les Chemins', pc: 'D♦', tone: 0, themes: ['changement'],
    kw: ['Choix', 'Carrefour', 'Options', 'Liberté'],
    sens: 'Les Chemins se séparent : une décision est à prendre et plusieurs options s’offrent à toi. Cette carte parle de liberté, mais aussi de responsabilité.',
    amour: 'Une hésitation entre deux voies ou deux personnes.',
    travail: 'Plusieurs pistes, une orientation à choisir.',
    conseil: 'Choisis la voie qui te ressemble.',
    nom: 'un choix à faire', mod: 'qui ouvre plusieurs possibilités' },
  { n: 23, name: 'Les Souris', pc: '7♣', tone: -1, themes: ['obstacles', 'argent'],
    kw: ['Usure', 'Stress', 'Petites pertes', 'Inquiétude'],
    sens: 'Les Souris grignotent : petits soucis, stress, pertes, énergie qui s’use. Elles montrent ce qui diminue en silence et qu’il vaut mieux régler tôt.',
    amour: 'Une lassitude qui s’installe, des inquiétudes.',
    travail: 'Pertes, erreurs, fatigue mentale.',
    conseil: 'Règle les petits problèmes avant qu’ils ne grossissent.',
    nom: 'une petite usure', mod: 'qui s’effrite peu à peu' },
  { n: 24, name: 'Le Cœur', pc: 'V♥', tone: 1, themes: ['amour'],
    kw: ['Amour', 'Tendresse', 'Sentiments', 'Générosité'],
    sens: 'Le Cœur parle d’amour sous toutes ses formes : sentiments, tendresse, affection. Il apporte chaleur, générosité et réconciliation.',
    amour: 'Des sentiments forts et partagés.',
    travail: 'Aimer ce que l’on fait, travailler avec passion.',
    conseil: 'Écoute ce que ton cœur te dit.',
    nom: 'un sentiment sincère', mod: 'qui vient du cœur' },
  { n: 25, name: 'L’Anneau', pc: 'A♣', tone: 1, themes: ['amour', 'travail'],
    kw: ['Engagement', 'Contrat', 'Union', 'Promesse'],
    sens: 'L’Anneau relie : union, contrat, promesse, partenariat. Il parle de fidélité à un engagement, et parfois de cycles qui se répètent.',
    amour: 'Un engagement, des fiançailles, un mariage.',
    travail: 'Un contrat signé, une association, un accord.',
    conseil: 'Honore tes promesses et choisis bien tes engagements.',
    nom: 'un engagement', mod: 'qui scelle une promesse' },
  { n: 26, name: 'Le Livre', pc: '10♦', tone: 0, themes: ['travail'],
    kw: ['Secret', 'Savoir', 'Études', 'Mystère'],
    sens: 'Le Livre est encore fermé : un secret, une connaissance à découvrir, des études. Quelque chose n’est pas encore révélé. Il parle aussi d’apprentissage et d’expertise.',
    amour: 'Des sentiments gardés secrets.',
    travail: 'Formation, recherche, dossier confidentiel.',
    conseil: 'Renseigne-toi avant de te prononcer.',
    nom: 'un secret', mod: 'qui garde encore son secret' },
  { n: 27, name: 'La Lettre', pc: '7♠', tone: 0, themes: ['communication'],
    kw: ['Message', 'Écrit', 'Document', 'Courrier'],
    sens: 'La Lettre apporte un message : courrier, e-mail, document, invitation. Elle parle de communication écrite et d’informations concrètes.',
    amour: 'Un message, une déclaration par écrit.',
    travail: 'Contrat, papier officiel, e-mail important.',
    conseil: 'Mets les choses par écrit.',
    nom: 'un message écrit', mod: 'qui passe par l’écrit' },
  { n: 28, name: 'L’Homme', pc: 'A♥', tone: 0, themes: ['relations'],
    kw: ['Consultant', 'Partenaire', 'Élan', 'Affirmation'],
    sens: 'L’Homme représente la personne qui consulte si c’est un homme, ou un homme important dans sa vie : partenaire, ami, proche. Il incarne aussi l’élan et l’affirmation de soi.',
    amour: 'Le partenaire, ou l’homme dont il est question.',
    travail: 'Un collègue, un interlocuteur, un décideur.',
    conseil: 'Affirme-toi avec calme.',
    nom: 'un homme', mod: 'qui prend les choses en main' },
  { n: 29, name: 'La Femme', pc: 'A♠', tone: 0, themes: ['relations'],
    kw: ['Consultante', 'Partenaire', 'Intuition', 'Accueil'],
    sens: 'La Femme représente la personne qui consulte si c’est une femme, ou une femme importante dans sa vie. Elle incarne aussi l’écoute, l’intuition et la capacité d’accueillir.',
    amour: 'La partenaire, ou la femme dont il est question.',
    travail: 'Une collègue, une interlocutrice, une décideuse.',
    conseil: 'Écoute ton intuition, elle voit juste.',
    nom: 'une femme', mod: 'qui agit avec intuition' },
  { n: 30, name: 'Le Lys', pc: 'R♠', tone: 1, themes: ['foyer', 'spirituel'],
    kw: ['Paix', 'Harmonie', 'Sagesse', 'Maturité'],
    sens: 'Le Lys apporte la paix et la sagesse : harmonie, maturité, bienveillance, parfois une personne plus âgée et de bon conseil. Il parle aussi d’une sensualité douce et sereine.',
    amour: 'Une tendresse apaisée, une relation mûre.',
    travail: 'Expérience, sérénité, mentor ou fin de carrière.',
    conseil: 'Privilégie le calme et la bienveillance.',
    nom: 'une paix profonde', mod: 'qui mûrit avec sérénité' },
  { n: 31, name: 'Le Soleil', pc: 'A♦', tone: 1, themes: ['chance'],
    kw: ['Réussite', 'Énergie', 'Joie', 'Confiance'],
    sens: 'Le Soleil est l’une des cartes les plus favorables du jeu : réussite, vitalité, confiance, bonheur. Il éclaire tout ce qui l’entoure.',
    amour: 'Une relation épanouie et joyeuse.',
    travail: 'Succès, reconnaissance, énergie débordante.',
    conseil: 'Crois en toi : c’est ton moment.',
    nom: 'une belle réussite', mod: 'qui rayonne de succès' },
  { n: 32, name: 'La Lune', pc: '8♥', tone: 1, themes: ['spirituel'],
    kw: ['Émotions', 'Intuition', 'Reconnaissance', 'Créativité'],
    sens: 'La Lune parle d’émotions, d’intuition et de sensibilité, mais aussi de reconnaissance et de réputation. C’est la carte des artistes, des rêves et du monde intérieur.',
    amour: 'Romantisme, émotions intenses, forte attirance.',
    travail: 'Reconnaissance, créativité, notoriété.',
    conseil: 'Fais confiance à ce que tu ressens.',
    nom: 'une intuition', mod: 'qui touche les émotions' },
  { n: 33, name: 'La Clé', pc: '8♦', tone: 1, themes: ['chance'],
    kw: ['Solution', 'Certitude', 'Ouverture', 'Importance'],
    sens: 'La Clé ouvre les portes : une solution, une certitude, une réussite assurée. Elle souligne aussi ce qui compte vraiment dans la situation.',
    amour: 'Le lien est sûr, une porte s’ouvre.',
    travail: 'La solution est trouvée, un rôle clé se présente.',
    conseil: 'La réponse est entre tes mains.',
    nom: 'une solution', mod: 'qui ouvre la voie' },
  { n: 34, name: 'Les Poissons', pc: 'R♦', tone: 1, themes: ['argent'],
    kw: ['Argent', 'Abondance', 'Affaires', 'Indépendance'],
    sens: 'Les Poissons nagent dans l’abondance : argent, affaires, échanges, autonomie financière. Ils parlent aussi de ce qui circule librement.',
    amour: 'Générosité, liberté laissée à chacun.',
    travail: 'Gains, affaires, commerce, travail indépendant.',
    conseil: 'Fais circuler tes ressources avec sagesse.',
    nom: 'l’abondance', mod: 'qui fait fructifier les ressources' },
  { n: 35, name: 'L’Ancre', pc: '9♠', tone: 1, themes: ['travail'],
    kw: ['Stabilité', 'Persévérance', 'Ancrage', 'Durée'],
    sens: 'L’Ancre stabilise : sécurité, persévérance, objectif atteint. Elle parle de ce qui tient bon, souvent dans le travail, et d’un port sûr après la traversée.',
    amour: 'Un lien stable et durable.',
    travail: 'Un emploi stable, une persévérance récompensée.',
    conseil: 'Tiens bon, tu es sur la bonne voie.',
    nom: 'une base solide', mod: 'qui tient dans la durée' },
  { n: 36, name: 'La Croix', pc: '6♣', tone: -1, themes: ['spirituel', 'obstacles'],
    kw: ['Épreuve', 'Destin', 'Responsabilité', 'Sens'],
    sens: 'La Croix parle de ce qui pèse et de ce qui a du sens : une épreuve, une responsabilité, parfois une dimension spirituelle. Elle rappelle que certaines difficultés font grandir.',
    amour: 'Une relation vécue comme un devoir, ou un lien qui semble écrit d’avance.',
    travail: 'Une lourde charge, une mission importante.',
    conseil: 'Porte ce qui compte, dépose ce qui ne t’appartient pas.',
    nom: 'une épreuve', mod: 'qui porte un sens profond' },
];

// Tirages : positions dans l'ordre du tirage. `area` place la carte dans la grille.
export const SPREADS = [
  { id: 'jour', name: 'Carte du jour', count: 1, cols: 1,
    desc: 'Une seule carte pour éclairer ta journée ou répondre à une question simple.',
    positions: [{ label: 'Le message du jour', hint: 'L’énergie qui t’accompagne aujourd’hui.' }] },
  { id: 'trois', name: 'Trois cartes', count: 3, cols: 3,
    desc: 'Le tirage classique : trois cartes lues de gauche à droite, comme une petite phrase.',
    positions: [
      { label: 'Ce qui précède', hint: 'Ce qui a mené à la situation.' },
      { label: 'Le cœur de la situation', hint: 'Ce qui se joue en ce moment.' },
      { label: 'Ce qui se dessine', hint: 'La tendance qui se prépare.' },
    ] },
  { id: 'cinq', name: 'Ligne de cinq', count: 5, cols: 5,
    desc: 'Cinq cartes en ligne : le passé à gauche, le cœur de la question au centre, la suite à droite.',
    positions: [
      { label: 'Les racines', hint: 'Ce qui est derrière toi.' },
      { label: 'L’influence récente', hint: 'Ce qui a compté dernièrement.' },
      { label: 'Le cœur de la question', hint: 'La carte centrale donne le ton.' },
      { label: 'L’évolution', hint: 'Ce qui arrive bientôt.' },
      { label: 'L’issue', hint: 'La direction la plus probable.' },
    ] },
  { id: 'croix', name: 'La croix', count: 5, cols: 3,
    desc: 'Une carte au centre, entourée de ce qui l’a précédée, de ce qui la suit, de ce qui l’éclaire et de ce qui la soutient.',
    positions: [
      { label: 'Le cœur de la question', hint: 'La situation telle qu’elle est.', area: 'c' },
      { label: 'Le passé', hint: 'Ce qui vient d’avant.', area: 'l' },
      { label: 'L’avenir', hint: 'Ce vers quoi tu te diriges.', area: 'r' },
      { label: 'Ce qui éclaire', hint: 'Ce qui peut t’aider ou te guider.', area: 't' },
      { label: 'Ce qui agit en profondeur', hint: 'Ce qui soutient ou freine en coulisses.', area: 'b' },
    ] },
  { id: 'neuf', name: 'Carré de neuf', count: 9, cols: 3,
    desc: 'Neuf cartes en carré : les colonnes vont du passé à l’avenir, les lignes vont des pensées aux coulisses. La carte du centre résume la question.',
    positions: [
      { label: 'Passé · pensées', hint: 'Ce qui occupait ton esprit.' },
      { label: 'Présent · pensées', hint: 'Ce qui occupe ton esprit.' },
      { label: 'Avenir · pensées', hint: 'Ce qui va occuper ton esprit.' },
      { label: 'Passé · vécu', hint: 'Ce qui a mené ici.' },
      { label: 'Le cœur de la question', hint: 'Ce qui se vit maintenant.' },
      { label: 'Avenir · vécu', hint: 'Ce qui se prépare.' },
      { label: 'Passé · coulisses', hint: 'Ce qui a joué en silence.' },
      { label: 'Présent · coulisses', hint: 'Ce qui agit sans se montrer.' },
      { label: 'Avenir · coulisses', hint: 'Ce qui mûrit en secret.' },
    ] },
];

// Remarques mises en avant quand certaines cartes sortent (par ordre d'importance).
export const NOTES = [
  { all: [24, 25], text: 'Le Cœur et l’Anneau sortent ensemble : un engagement sincère est au centre du tirage.' },
  { all: [28, 29], text: 'L’Homme et la Femme apparaissent tous les deux : la relation entre deux personnes est au cœur de la question.' },
  { all: [33], text: 'La Clé est présente : une solution existe, et elle est plus proche qu’il n’y paraît.' },
  { all: [31], text: 'Le Soleil illumine le tirage : l’énergie est porteuse et l’issue promet d’être heureuse.' },
  { all: [8], text: 'Le Cercueil signale qu’un cycle se termine : laisser partir l’ancien fera de la place au nouveau.' },
  { all: [36], text: 'La Croix invite à distinguer ce qui mérite d’être porté de ce qui pèse inutilement.' },
  { all: [21], text: 'La Montagne annonce un retard, pas un échec : la persévérance finira par payer.' },
  { all: [6], text: 'Les Nuages conseillent de ne rien décider dans la confusion : attends d’y voir plus clair.' },
  { all: [7], text: 'Le Serpent demande de rester attentif aux détours et aux intentions qui ne se montrent pas.' },
  { all: [22], text: 'Les Chemins rappellent que le choix t’appartient : plusieurs issues restent ouvertes.' },
  { all: [1], text: 'Le Cavalier indique que les choses peuvent bouger vite : une nouvelle est en route.' },
  { all: [24], text: 'Le Cœur rappelle que les sentiments jouent ici un grand rôle.' },
  { all: [16], text: 'Les Étoiles encouragent à garder confiance : tes souhaits sont soutenus.' },
  { all: [23], text: 'Les Souris invitent à régler sans attendre les petits soucis qui s’accumulent.' },
  { all: [28], text: 'L’Homme représente toi-même ou un homme important : les cartes qui l’entourent le concernent de près.' },
  { all: [29], text: 'La Femme représente toi-même ou une femme importante : les cartes qui l’entourent la concernent de près.' },
];

// Livret : règles et conseils (HTML).
export const RULES = `
<h4>Le jeu</h4>
<p>Le Petit Lenormand compte <b>36 cartes</b> illustrées de scènes et d’objets du quotidien : une maison, un navire, un cœur, une clé… Il porte le nom de Marie-Anne Lenormand, cartomancienne parisienne très célèbre à l’époque de Napoléon. Le jeu n’a pourtant été publié qu’après sa mort, en reprenant un jeu de société allemand de la fin du XVIIIᵉ siècle.</p>
<p>Chaque carte porte aussi, en petit, une carte à jouer (par exemple 9♥ pour le Cavalier) héritée de ce jeu d’origine.</p>

<h4>Lire les cartes</h4>
<ul>
  <li><b>Un langage concret.</b> Chaque carte est comme un mot ; c’est l’assemblage des cartes qui forme une phrase.</li>
  <li><b>La lecture en paires.</b> La première carte désigne le sujet, la suivante le précise ou le colore. <i>Cavalier + Cœur</i> : une nouvelle qui vient du cœur. <i>Cœur + Cavalier</i> : des sentiments qui arrivent vite.</li>
  <li><b>Les voisines comptent.</b> Une carte lumineuse adoucit une voisine difficile, et une carte délicate tempère une voisine favorable.</li>
  <li><b>Les cartes-personnes.</b> L’Homme et la Femme représentent la personne qui consulte, ou la personne dont on parle. Les cartes proches d’elles la concernent directement.</li>
  <li><b>Des tendances, pas des sentences.</b> Certaines cartes sont réputées favorables (Soleil, Trèfle, Étoiles, Clé, Bouquet…), d’autres appellent à la prudence (Nuages, Serpent, Cercueil, Montagne, Souris, Croix…). Aucune n’est une condamnation : elles décrivent un climat.</li>
</ul>

<h4>Préparer un tirage</h4>
<ol>
  <li>Prends un moment calme et formule une question claire et ouverte : « Que dois-je savoir sur… » plutôt que « Est-ce que… ».</li>
  <li>Choisis un tirage adapté : une carte pour un conseil, trois pour une situation simple, davantage pour creuser.</li>
  <li>Mélange en pensant à ta question, puis tire les cartes.</li>
  <li>Lis d’abord chaque carte à sa place, puis l’ensemble : l’histoire racontée par les cartes compte plus que chaque carte seule.</li>
</ol>
<p class="le-disclaimer">Ce jeu est proposé pour la réflexion et le plaisir. Il ne remplace pas l’avis d’un professionnel, en particulier pour la santé, le droit ou l’argent.</p>`;
